// Configuração e lista inicial usadas pelo armazenamento local (desenvolvimento).
// A versão de produção dos mesmos dados está na migração em supabase/migrations.
import type { Product, Settings } from "./types";

export const DEFAULT_SETTINGS: Settings = {
  campaignName: "Culto Kids",
  institutionName: "CBVIDA RIO",
  campaignDeadline: "2026-12-15T23:59:59-03:00",
  campaignActive: true,
  pixKey: "+5521986422434",
  pixRecipient: "",
  pixCity: "RIO DE JANEIRO",
  pixQrEnabled: true,
  deliveryLocation: "Na CBVIDA RIO",
  campaignMessage:
    "Estamos preparando um Culto Kids muito especial para aproximadamente 100 crianças e você pode fazer parte desse momento conosco.",
  childrenGoal: 100,
  showSupporters: true,
};

type Seed = [string, string, string, number, string, string, number, number, string, number];

const SEED: Seed[] = [
  ["Pães", "Cachorro-quente", "20 pães de cachorro-quente", 20, "pão", "pães", 6, 20, "🥖", 10],
  [
    "Salsicha",
    "Cachorro-quente",
    "1 kg de salsicha",
    1,
    "kg de salsicha",
    "kg de salsicha",
    7,
    15,
    "🌭",
    20,
  ],
  [
    "Molho de tomate",
    "Cachorro-quente",
    "2 unidades de molho de tomate",
    2,
    "molho de tomate",
    "molhos de tomate",
    3,
    10,
    "🍅",
    30,
  ],
  [
    "Milho",
    "Cachorro-quente",
    "2 latas/sachês de milho",
    2,
    "lata/sachê de milho",
    "latas/sachês de milho",
    3,
    12,
    "🌽",
    40,
  ],
  [
    "Batata palha",
    "Cachorro-quente",
    "1 kg de batata palha",
    1,
    "kg de batata palha",
    "kg de batata palha",
    3,
    30,
    "🥔",
    50,
  ],
  [
    "Ketchup",
    "Cachorro-quente",
    "1 ketchup grande",
    1,
    "ketchup grande",
    "ketchups grandes",
    2,
    15,
    "🥫",
    60,
  ],
  [
    "Maionese",
    "Cachorro-quente",
    "1 maionese grande",
    1,
    "maionese grande",
    "maioneses grandes",
    2,
    15,
    "🫙",
    70,
  ],
  [
    "Mostarda",
    "Cachorro-quente",
    "1 mostarda grande",
    1,
    "mostarda grande",
    "mostardas grandes",
    2,
    12,
    "🧴",
    80,
  ],
  [
    "Milho para pipoca",
    "Pipoca",
    "1 kg de milho para pipoca",
    1,
    "kg de milho",
    "kg de milho",
    5,
    12,
    "🍿",
    110,
  ],
  ["Balas", "Doces", "100 balas", 100, "bala", "balas", 5, 20, "🍬", 210],
  ["Pirulitos", "Doces", "30 pirulitos", 30, "pirulito", "pirulitos", 4, 20, "🍭", 220],
  [
    "Chocolates",
    "Doces",
    "30 chocolates pequenos/Bis",
    30,
    "chocolate",
    "chocolates",
    4,
    30,
    "🍫",
    230,
  ],
  [
    "Mini bolinhos / cupcakes",
    "Doces",
    "25 mini bolinhos/cupcakes",
    25,
    "unidade",
    "unidades",
    4,
    40,
    "🧁",
    240,
  ],
  [
    "Refrigerante",
    "Bebidas",
    "3 refrigerantes de 2 litros",
    3,
    "refrigerante de 2 L",
    "refrigerantes de 2 L",
    5,
    30,
    "🥤",
    310,
  ],
  ["Suco", "Bebidas", "2 sucos de 2 litros", 2, "suco de 2 L", "sucos de 2 L", 5, 20, "🧃", 320],
  ["Água", "Bebidas", "1 fardo de água", 1, "fardo de água", "fardos de água", 2, 25, "💧", 330],
  [
    "Copos descartáveis",
    "Descartáveis",
    "50 copos descartáveis",
    50,
    "copo",
    "copos",
    4,
    10,
    "🥛",
    410,
  ],
  [
    "Guardanapos",
    "Descartáveis",
    "50 guardanapos",
    50,
    "guardanapo",
    "guardanapos",
    4,
    8,
    "🧻",
    420,
  ],
  [
    "Sacos de lixo",
    "Descartáveis",
    "5 sacos de lixo grandes",
    5,
    "saco de lixo",
    "sacos de lixo",
    2,
    15,
    "🗑️",
    430,
  ],
];

export function seedProducts(now = new Date().toISOString()): Product[] {
  return SEED.map(
    ([
      name,
      category,
      unitDescription,
      unitAmount,
      unitSingular,
      unitPlural,
      totalUnits,
      estimatedPrice,
      icon,
      sortOrder,
    ]) => ({
      id: crypto.randomUUID(),
      name,
      category,
      description: "",
      unitDescription,
      unitAmount,
      unitSingular,
      unitPlural,
      totalUnits,
      estimatedPrice,
      icon,
      sortOrder,
      active: true,
      createdAt: now,
      updatedAt: now,
    }),
  );
}
